# Generated by Django 6.1 on 2026-10-01 01:29

import content.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def purge_legacy_delivery_cards(apps, schema_editor):
    """Authorized reset: only legacy cards/scope mirrors and their private trails.

    Bugs and change requests survive; Django's SET_NULL clears references to the
    cards. Commercial phases, proposals, documents, resources and finances are
    deliberately untouched. This step cannot recreate deleted legacy rows.
    """
    alias = schema_editor.connection.alias
    apps.get_model('accounts', 'Requirement').objects.using(alias).all().delete()
    apps.get_model('accounts', 'ProjectScopeItem').objects.using(alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_projectaccessnote_projectadminaccess'),
        ('content', '0273_merge_document_provenance_and_proposal_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(purge_legacy_delivery_cards, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_visible', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractSignatureEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, storage=content.storage.get_private_storage, upload_to='delivery/signatures/%Y/%m/')),
                ('sha256', models.CharField(max_length=64)),
                ('signer_name', models.CharField(max_length=255)),
                ('signed_at', models.DateTimeField()),
                ('attestation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryDocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryDocumentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(max_length=500, storage=content.storage.get_private_storage, upload_to='delivery/snapshots/%Y/%m/')),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('target_id', models.PositiveBigIntegerField()),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100)),
                ('fingerprint', models.CharField(max_length=64)),
                ('response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-round'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_current', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('editorial_status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Aprobado internamente')], default='draft', max_length=20)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_visible', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequirementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_version', models.PositiveIntegerField()),
                ('content_snapshot', models.JSONField(default=dict)),
                ('decision', models.CharField(choices=[('pending', 'Pendiente de publicación'), ('in_review', 'En revisión'), ('approved', 'Aprobado'), ('objected', 'Objetado'), ('rejected', 'Rechazado')], max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('environment', models.CharField(blank=True, default='', max_length=200)),
                ('is_external', models.BooleanField(default=False)),
                ('client_statement', models.TextField(blank=True, default='')),
                ('original_reviewer', models.CharField(blank=True, default='', max_length=300)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('evidence_document_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='projectscopeitem',
            name='uniq_scope_item_phase_source',
        ),
        migrations.RemoveField(
            model_name='requirementcomment',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='requirementcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='requirementhistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='requirementhistory',
            name='requirement',
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='requirement',
            name='uniq_requirement_phase_flow_key',
        ),
        migrations.RemoveField(
            model_name='bugreport',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='phase',
        ),
        migrations.AddField(
            model_name='requirement',
            name='guide',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='requirement',
            name='key',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirement',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pendiente de publicación'), ('in_review', 'En revisión'), ('approved', 'Aprobado'), ('objected', 'Objetado'), ('rejected', 'Rechazado')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='requirement',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_amendments', to='content.document'),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='proposal_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_amendments', to='content.proposaldocument'),
        ),
        migrations.AddField(
            model_name='contractsignatureevidence',
            name='amendment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signature_evidence', to='accounts.contractamendment'),
        ),
        migrations.AddField(
            model_name='contractsignatureevidence',
            name='attested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_signature_attestations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverydocumentlink',
            name='amendment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='accounts.contractamendment'),
        ),
        migrations.AddField(
            model_name='deliverydocumentlink',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_document_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverydocumentlink',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_links', to='content.document'),
        ),
        migrations.AddField(
            model_name='deliverydocumentlink',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_documents', to='accounts.project'),
        ),
        migrations.AddField(
            model_name='deliverydocumentlink',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='accounts.requirement'),
        ),
        migrations.AddField(
            model_name='deliverydocumentsnapshot',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='accounts.deliverydocumentlink'),
        ),
        migrations.AddField(
            model_name='deliverymessage',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverymessage',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='delivery_messages', to='content.document'),
        ),
        migrations.AddField(
            model_name='deliverymessage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_messages', to='accounts.project'),
        ),
        migrations.AddField(
            model_name='deliverymessage',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='delivery_messages', to='accounts.requirement'),
        ),
        migrations.AddField(
            model_name='deliveryoperation',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryoperation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_operations', to='accounts.project'),
        ),
        migrations.AddField(
            model_name='deliveryphase',
            name='commercial_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_phases', to='accounts.projectphase'),
        ),
        migrations.AddField(
            model_name='deliverydocumentlink',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='accounts.deliveryphase'),
        ),
        migrations.AddField(
            model_name='deliverypublication',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverydocumentsnapshot',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_snapshots', to='accounts.deliverypublication'),
        ),
        migrations.AddField(
            model_name='deliveryscope',
            name='amendment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scopes', to='accounts.contractamendment'),
        ),
        migrations.AddField(
            model_name='deliveryphase',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='accounts.deliveryscope'),
        ),
        migrations.AddField(
            model_name='deliverydocumentlink',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='accounts.deliveryscope'),
        ),
        migrations.AddField(
            model_name='deliverystage',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='accounts.deliveryphase'),
        ),
        migrations.AddField(
            model_name='deliverypublication',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='accounts.deliverystage'),
        ),
        migrations.AddField(
            model_name='deliverydocumentlink',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='accounts.deliverystage'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='accounts.deliverystage'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(fields=('stage', 'key'), name='delivery_requirement_key'),
        ),
        migrations.AddField(
            model_name='deliveryworkspace',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_workspace', to='accounts.project'),
        ),
        migrations.AddField(
            model_name='projectcontract',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_contracts', to='content.document'),
        ),
        migrations.AddField(
            model_name='projectcontract',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_contracts', to='accounts.project'),
        ),
        migrations.AddField(
            model_name='projectcontract',
            name='proposal_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_contracts', to='content.proposaldocument'),
        ),
        migrations.AddField(
            model_name='deliveryscope',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scopes', to='accounts.projectcontract'),
        ),
        migrations.AddField(
            model_name='deliverydocumentlink',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='accounts.projectcontract'),
        ),
        migrations.AddField(
            model_name='contractsignatureevidence',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signature_evidence', to='accounts.projectcontract'),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='accounts.projectcontract'),
        ),
        migrations.AddField(
            model_name='requirementreview',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requirementreview',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='accounts.deliverypublication'),
        ),
        migrations.AddField(
            model_name='requirementreview',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='accounts.requirement'),
        ),
        migrations.AddField(
            model_name='requirementreview',
            name='source_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_approvals', to='content.communicationmessage'),
        ),
        migrations.RemoveField(
            model_name='projectscopeitem',
            name='phase',
        ),
        migrations.DeleteModel(
            name='RequirementComment',
        ),
        migrations.DeleteModel(
            name='RequirementHistory',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='content_overridden',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='scope_item',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='source_epic_key',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='source_epic_title',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='source_flow_key',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='synced_from_proposal',
        ),
        migrations.AddConstraint(
            model_name='deliveryoperation',
            constraint=models.UniqueConstraint(fields=('project', 'request_id'), name='delivery_operation_key'),
        ),
        migrations.AddConstraint(
            model_name='deliverydocumentsnapshot',
            constraint=models.UniqueConstraint(fields=('publication', 'link'), name='delivery_document_snapshot_link'),
        ),
        migrations.AddConstraint(
            model_name='deliveryphase',
            constraint=models.UniqueConstraint(fields=('scope', 'key'), name='delivery_phase_key'),
        ),
        migrations.AddConstraint(
            model_name='deliverystage',
            constraint=models.UniqueConstraint(fields=('phase', 'key'), name='delivery_stage_key'),
        ),
        migrations.AddConstraint(
            model_name='deliverypublication',
            constraint=models.UniqueConstraint(fields=('stage', 'round'), name='delivery_publication_round'),
        ),
        migrations.AddConstraint(
            model_name='projectcontract',
            constraint=models.UniqueConstraint(fields=('project', 'key'), name='delivery_contract_key'),
        ),
        migrations.AddConstraint(
            model_name='projectcontract',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document__isnull', False), ('proposal_document__isnull', True)), models.Q(('document__isnull', True), ('proposal_document__isnull', False)), _connector='OR'), name='delivery_contract_one_source'),
        ),
        migrations.AddConstraint(
            model_name='deliveryscope',
            constraint=models.UniqueConstraint(fields=('contract', 'key'), name='delivery_scope_key'),
        ),
        migrations.AddConstraint(
            model_name='contractsignatureevidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amendment__isnull', True), ('contract__isnull', False)), models.Q(('amendment__isnull', False), ('contract__isnull', True)), _connector='OR'), name='delivery_signature_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='contractamendment',
            constraint=models.UniqueConstraint(fields=('contract', 'key'), name='delivery_amendment_key'),
        ),
        migrations.AddConstraint(
            model_name='contractamendment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document__isnull', False), ('proposal_document__isnull', True)), models.Q(('document__isnull', True), ('proposal_document__isnull', False)), _connector='OR'), name='delivery_amendment_one_source'),
        ),
        migrations.DeleteModel(
            name='ProjectScopeItem',
        ),
    ]
