# Generated by Django 6.1 on 2026-10-01 12:20

import content.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_delivery_review_document_evidence'),
        ('content', '0273_merge_document_provenance_and_proposal_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymessage',
            name='reply_classifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deliverymessage',
            name='source_references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='requirement',
            name='source_references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='DeliveryPromptContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('guides', 'Crear guías'), ('reply', 'Preparar respuesta')], max_length=12)),
                ('request_id', models.CharField(max_length=100)),
                ('fingerprint', models.CharField(max_length=64)),
                ('captured_version', models.PositiveIntegerField()),
                ('amendment_ids', models.JSONField(default=list)),
                ('missing_sources', models.JSONField(default=list)),
                ('uncertainties', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('complete', models.BooleanField(default=False)),
                ('prompt', models.TextField()),
                ('template', models.JSONField(default=dict)),
                ('schema', models.JSONField(default=dict)),
                ('conversation', models.JSONField(default=dict)),
                ('manifest_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_prompt_contexts', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prompt_contexts', to='accounts.projectcontract')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_prompt_contexts', to='accounts.project')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prompt_contexts', to='accounts.deliveryscope')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prompt_contexts', to='accounts.deliverystage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deliverymessage',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='accounts.deliverypromptcontext'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='accounts.deliverypromptcontext'),
        ),
        migrations.CreateModel(
            name='DeliveryPromptSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('origin', models.CharField(max_length=32)),
                ('source_id', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=32)),
                ('applicability_note', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('version_kind', models.CharField(default='unknown', max_length=30)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, max_length=500, storage=content.storage.get_private_storage, upload_to='delivery/prompt-sources/%Y/%m/')),
                ('filename', models.CharField(blank=True, default='', max_length=300)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('snapshot', models.JSONField(default=dict)),
                ('fragments', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('included', 'Incluida'), ('missing', 'Faltante'), ('unreadable', 'Ilegible'), ('partial', 'Parcial')], max_length=16)),
                ('warnings', models.JSONField(default=list)),
                ('limits', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='accounts.deliverypromptcontext')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_prompt_sources', to='content.document')),
                ('proposal_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_prompt_sources', to='content.proposaldocument')),
                ('signature_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prompt_sources', to='accounts.contractsignatureevidence')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='deliverypromptcontext',
            constraint=models.UniqueConstraint(fields=('project', 'request_id'), name='delivery_prompt_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='deliverypromptsource',
            constraint=models.UniqueConstraint(fields=('context', 'source_key'), name='delivery_prompt_source_unique'),
        ),
    ]
