# Generated by Django 6.1 on 2026-10-01 14:04

import content.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_delivery_review_document_evidence'),
        ('content', '0273_merge_document_provenance_and_proposal_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='status',
            field=models.CharField(choices=[('reported', 'Reportado'), ('confirmed', 'Confirmado'), ('fixing', 'En corrección'), ('qa', 'En QA'), ('resolved', 'Resuelto por equipo'), ('not_reproducible', 'No reproducible'), ('wont_fix', 'No se corregirá'), ('duplicate', 'Duplicado')], default='reported', max_length=25),
        ),
        migrations.CreateModel(
            name='IssueResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(max_length=25)),
                ('is_internal', models.BooleanField(default=False)),
                ('scope_result', models.CharField(choices=[('within_scope', 'Dentro del alcance'), ('outside_scope', 'Fuera del alcance'), ('indeterminate', 'Indeterminado')], default='indeterminate', max_length=20)),
                ('review_evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('bug_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_responses', to='accounts.bugreport')),
                ('change_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_responses', to='accounts.changerequest')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_responses', to='accounts.projectcontract')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='IssueAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(storage=content.storage.get_private_storage, upload_to='issue_evidence/%Y/%m/')),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bug_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_attachments', to='accounts.bugcomment')),
                ('change_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_attachments', to='accounts.changerequestcomment')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_attachments', to='content.document')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounts.issueresponse')),
            ],
        ),
        migrations.CreateModel(
            name='IssueContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bug_report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_context', to='accounts.bugreport')),
                ('change_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_context', to='accounts.changerequest')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_contexts', to='accounts.deliverypublication')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('bug_report__isnull', False), ('change_request__isnull', True)), models.Q(('bug_report__isnull', True), ('change_request__isnull', False)), _connector='OR'), name='issue_context_one_ticket')],
            },
        ),
        migrations.CreateModel(
            name='IssueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('previous_status', models.CharField(blank=True, default='', max_length=25)),
                ('status', models.CharField(max_length=25)),
                ('is_internal', models.BooleanField(default=False)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('receipt', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('bug_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_events', to='accounts.bugreport')),
                ('change_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_events', to='accounts.changerequest')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('bug_report__isnull', False), ('change_request__isnull', True)), models.Q(('bug_report__isnull', True), ('change_request__isnull', False)), _connector='OR'), name='issue_event_one_ticket'), models.UniqueConstraint(fields=('project', 'actor', 'request_id'), name='issue_retry_receipt')],
            },
        ),
        migrations.AddConstraint(
            model_name='issueresponse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bug_report__isnull', False), ('change_request__isnull', True)), models.Q(('bug_report__isnull', True), ('change_request__isnull', False)), _connector='OR'), name='issue_response_one_ticket'),
        ),
        migrations.AddConstraint(
            model_name='issueattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bug_comment__isnull', True), ('change_comment__isnull', True), ('response__isnull', False)), models.Q(('bug_comment__isnull', False), ('change_comment__isnull', True), ('response__isnull', True)), models.Q(('bug_comment__isnull', True), ('change_comment__isnull', False), ('response__isnull', True)), _connector='OR'), name='issue_attachment_one_message'),
        ),
    ]
