# Generated by Django 6.1 on 2026-10-01 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_explicit_delivery_authoring_context'),
        ('content', '0273_merge_document_provenance_and_proposal_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingContextEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_context_events', to='content.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_context_events', to='accounts.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectHosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_hosting', to='accounts.project')),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_context', to='accounts.hostingsubscription')),
            ],
        ),
        migrations.CreateModel(
            name='HostingEvidenceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hosting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_groups', to='accounts.projecthosting')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectHostingAccountingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hosting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_sources', to='accounts.projecthosting')),
                ('hosting_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_source', to='content.hostingrecord')),
            ],
        ),
        migrations.AddField(
            model_name='projecthosting',
            name='operational_accounting_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.projecthostingaccountingsource'),
        ),
        migrations.CreateModel(
            name='HostingEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_evidence', to='content.hostingcycle')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hosting_evidence', to='content.document')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_evidence', to='accounts.payment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='accounts.hostingevidencegroup')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cycle__isnull', True), ('document__isnull', True), ('payment__isnull', False)), models.Q(('cycle__isnull', False), ('document__isnull', True), ('payment__isnull', True)), models.Q(('cycle__isnull', True), ('document__isnull', False), ('payment__isnull', True)), _connector='OR'), name='billing_evidence_one_reference')],
            },
        ),
        migrations.CreateModel(
            name='CollectionAccountContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('contract', 'Contrato'), ('hosting', 'Hosting')], max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amendment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_contexts', to='accounts.contractamendment')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_contexts', to='accounts.projectcontract')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_context', to='content.document')),
                ('hosting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_contexts', to='accounts.projecthosting')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('contract__isnull', False), ('hosting__isnull', True), ('nature', 'contract')), models.Q(('amendment__isnull', True), ('contract__isnull', True), ('hosting__isnull', False), ('nature', 'hosting')), _connector='OR'), name='billing_account_exclusive_nature')],
            },
        ),
    ]
