# Generated by Django 6.1 on 2026-10-01 18:04

import content.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_explicit_delivery_authoring_context'),
        ('content', '0273_merge_document_provenance_and_proposal_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypromptcontext',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_prompt_client_contexts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverypromptcontext',
            name='destination',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='deliverypromptcontext',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prompt_contexts', to='accounts.projectcontract'),
        ),
        migrations.CreateModel(
            name='DeliveryEvidenceEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_recipients', models.JSONField(default=list)),
                ('from_email', models.CharField(max_length=320)),
                ('subject', models.CharField(max_length=500)),
                ('html_body', models.TextField()),
                ('text_body', models.TextField()),
                ('snapshot_payload', models.JSONField(default=dict)),
                ('closure_history', models.JSONField(default=dict)),
                ('captured_version', models.PositiveIntegerField()),
                ('request_id', models.CharField(max_length=100)),
                ('manifest_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_closure_emails', to=settings.AUTH_USER_MODEL)),
                ('mcp_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_delivery_closure_emails', to='content.mcpcredential')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_delivery_closure_emails', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_closure_emails', to='accounts.project')),
                ('resend_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resend_preparations', to='accounts.deliveryevidenceemail')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closure_emails', to='accounts.deliverystage')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvidenceEmailAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('unknown', 'Desconocido')], default='pending', max_length=12)),
                ('error_message', models.TextField(blank=True, default='')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_closure_email_attempts', to=settings.AUTH_USER_MODEL)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='accounts.deliveryevidenceemail')),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_closure_email_attempts', to='content.emaillog')),
                ('gateway_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_closure_email_attempts', to='content.emaildeliverysnapshot')),
                ('mcp_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_closure_email_attempts', to='content.mcpcredential')),
                ('resend_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retries', to='accounts.deliveryevidenceemailattempt')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvidenceEmailFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, storage=content.storage.get_private_storage, upload_to='delivery/closure-emails/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('position', models.PositiveIntegerField()),
                ('delivery_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closure_email_files', to='accounts.deliverydocumentsnapshot')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='accounts.deliveryevidenceemail')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='deliveryevidenceemail',
            index=models.Index(fields=['stage', 'created_at'], name='accounts_de_stage_i_98fa9a_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryevidenceemail',
            index=models.Index(fields=['client', 'created_at'], name='accounts_de_client__beddd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryevidenceemail',
            constraint=models.UniqueConstraint(fields=('project', 'request_id'), name='delivery_closure_email_request_unique'),
        ),
        migrations.AddIndex(
            model_name='deliveryevidenceemailattempt',
            index=models.Index(fields=['email', 'status'], name='accounts_de_email_i_b77629_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryevidenceemailattempt',
            constraint=models.UniqueConstraint(fields=('email', 'request_id'), name='delivery_closure_email_attempt_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='deliveryevidenceemailfile',
            constraint=models.UniqueConstraint(fields=('email', 'position'), name='delivery_closure_email_file_position_unique'),
        ),
    ]
