# Generated by Django 6.1 on 2026-10-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_p4_platform_domains_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
