# Generated by Django 6.1 on 2026-10-06 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_userprofile_billing_address'),
        ('content', '0281_project_data_retention'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='deliverydocumentlink',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='deliverymessage',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='deliveryoperation',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='deliveryworkspace',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='hostingsubscription',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='issuecontext',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='issueevent',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='notification',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='projectaccessnote',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='projectadminaccess',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='projectclientaccessevent',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='projectclientaccesspolicy',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='projectcontract',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='projectdatamodelentity',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='projecthosting',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='projectidea',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='projectideacollection',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bug_reports', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='deliverydocumentlink',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_documents', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='deliverymessage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_messages', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='deliveryoperation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_operations', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='deliveryworkspace',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_workspace', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='hostingsubscription',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hosting_subscription', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='issuecontext',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='issueevent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project context for deep-linking.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='projectaccessnote',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_notes', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='projectadminaccess',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_accesses', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='projectclientaccessevent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_access_events', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='projectclientaccesspolicy',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_access_policy', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='projectcontract',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_contracts', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='projectdatamodelentity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_data_model_entities', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='projecthosting',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_hosting', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='projectidea',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ideas', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='projectideacollection',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idea_collections', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phases', to='accounts.project'),
        ),
    ]
