# Generated by Django 6.1.2 on 2026-10-07 00:56

import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


def backfill_proposal_ownership(apps, schema_editor):
    """Adopt only technical keys supported by a single proposal's source data."""
    Deliverable = apps.get_model('accounts', 'Deliverable')
    Phase = apps.get_model('accounts', 'ProjectPhase')
    Proposal = apps.get_model('content', 'BusinessProposal')
    Section = apps.get_model('content', 'ProposalSection')
    alias = schema_editor.connection.alias
    owners = {}
    for project_id, proposal_id in Phase.objects.using(alias).values_list('project_id', 'business_proposal_id'):
        owners.setdefault(project_id, set()).add(proposal_id)
    for project_id, proposal_id in Proposal.objects.using(alias).filter(deliverable__isnull=False).values_list('deliverable__project_id', 'pk'):
        owners.setdefault(project_id, set()).add(proposal_id)
    for project_id, candidates in owners.items():
        if project_id is None or len(candidates) != 1:
            continue
        proposal_id = next(iter(candidates))
        proposal = Proposal.objects.using(alias).get(pk=proposal_id)
        manifest = proposal.platform_approval_manifest or {}
        if isinstance(manifest, dict) and 'technical_content' in manifest:
            documents = [manifest['technical_content']]
        else:
            documents = Section.objects.using(alias).filter(proposal_id=proposal_id, section_type='technical_document', is_enabled=True).values_list('content_json', flat=True)
        keys = set()
        for document in documents:
            if not isinstance(document, dict) or not isinstance(document.get('epics'), list):
                continue
            for index, epic in enumerate(document['epics']):
                if not isinstance(epic, dict):
                    continue
                key = str(epic.get('epicKey') or '').strip()
                if not key and isinstance(epic.get('requirements'), list) and epic['requirements']:
                    key = f'_sync_epic_{index}'
                if key:
                    keys.add(key)
        if keys:
            Deliverable.objects.using(alias).filter(project_id=project_id, source_proposal__isnull=True, source_epic_key__in=keys).update(source_proposal_id=proposal_id)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_project_data_retention'),
        ('content', '0283_proposal_project_reassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deliverable',
            name='uniq_deliverable_project_epic_key',
        ),
        migrations.AddField(
            model_name='deliverable',
            name='source_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_resources', to='content.businessproposal'),
        ),
        migrations.AddConstraint(
            model_name='deliverable',
            constraint=models.UniqueConstraint(models.F('project'), django.db.models.functions.comparison.Coalesce(models.F('source_proposal'), models.Value(0)), django.db.models.functions.comparison.NullIf(models.F('source_epic_key'), models.Value('')), name='uniq_deliverable_proposal_epic_key'),
        ),
        migrations.RunPython(backfill_proposal_ownership, migrations.RunPython.noop),
    ]
