# Generated by Django 6.1.2 on 2026-10-07 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_proposal_project_reassignment'),
        ('content', '0283_proposal_project_reassignment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contractamendment',
            name='delivery_amendment_one_source',
        ),
        migrations.RemoveConstraint(
            model_name='projectcontract',
            name='delivery_contract_one_source',
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='approval_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_amendments', to='content.proposalapprovalfile'),
        ),
        migrations.AddField(
            model_name='projectcontract',
            name='approval_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_contracts', to='content.proposalapprovalfile'),
        ),
        migrations.AddConstraint(
            model_name='contractamendment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approval_file__isnull', True), ('document__isnull', False), ('proposal_document__isnull', True)), models.Q(('approval_file__isnull', True), ('document__isnull', True), ('proposal_document__isnull', False)), models.Q(('approval_file__isnull', False), ('document__isnull', True), ('proposal_document__isnull', True)), _connector='OR'), name='delivery_amendment_one_source'),
        ),
        migrations.AddConstraint(
            model_name='projectcontract',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approval_file__isnull', True), ('document__isnull', False), ('proposal_document__isnull', True)), models.Q(('approval_file__isnull', True), ('document__isnull', True), ('proposal_document__isnull', False)), models.Q(('approval_file__isnull', False), ('document__isnull', True), ('proposal_document__isnull', True)), _connector='OR'), name='delivery_contract_one_source'),
        ),
    ]
