# Generated by Django 6.1.2 on 2026-10-07 19:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_delivery_approval_source'),
        ('content', '0283_proposal_project_reassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_key', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=40)),
                ('audience', models.CharField(choices=[('client', 'Cliente'), ('team', 'Equipo')], max_length=10)),
                ('recipients', models.JSONField(default=list)),
                ('from_email', models.CharField(max_length=320)),
                ('subject', models.CharField(max_length=500)),
                ('text_body', models.TextField()),
                ('html_body', models.TextField()),
                ('public_context', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('unknown', 'Resultado desconocido'), ('cancelled', 'Cancelado')], default='pending', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notification_events', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_delivery_notification_events', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notification_events', to='accounts.project')),
                ('retention_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DeliveryNotificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100)),
                ('preview_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('unknown', 'Resultado desconocido'), ('cancelled', 'Cancelado')], default='pending', max_length=12)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notice_attempts', to='content.mcpcredential')),
                ('gateway_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notice_attempts', to='content.emaildeliverysnapshot')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notification_attempts', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='accounts.deliverynotificationevent')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='deliverynotificationevent',
            index=models.Index(fields=['project', 'created_at'], name='accounts_de_project_e43dac_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverynotificationevent',
            index=models.Index(fields=['status', 'created_at'], name='accounts_de_status_7144d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverynotificationevent',
            constraint=models.UniqueConstraint(fields=('project', 'operation_key'), name='delivery_notice_operation_unique'),
        ),
        migrations.AddConstraint(
            model_name='deliverynotificationattempt',
            constraint=models.UniqueConstraint(fields=('event', 'request_id'), name='delivery_notice_attempt_unique'),
        ),
    ]
