# Generated by Django 6.1.2 on 2026-10-09 22:56

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ('accounts', '0081_private_platform_resource_files'),
    ]

    operations: ClassVar[list[migrations.AlterField]] = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('overdue', 'Vencido'), ('voided', 'Anulado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='from_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('overdue', 'Vencido'), ('voided', 'Anulado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='to_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('overdue', 'Vencido'), ('voided', 'Anulado')], max_length=20),
        ),
    ]
