"""
Symmetric cipher for project access credentials (Django admin passwords).

Stored ciphertext is a Fernet token (base64-encoded, URL-safe). The key must be a
valid Fernet key supplied by ``PROJECT_ACCESS_CIPHER_KEY`` or a private key file.
The environment value takes precedence; keys are never generated by this module.

If the key is missing, the encrypt/decrypt helpers raise
``ImproperlyConfigured``. Empty inputs are returned as empty strings so callers
can treat "no secret saved" uniformly.

The default file is ``PRIVATE_MEDIA_ROOT/runtime-secrets/project-access.key``.
An operator can override it with ``PROJECT_ACCESS_CIPHER_KEY_FILE``. The key file
must stay outside Git and public media, and be backed up before using it.
"""

from __future__ import annotations

import os
import stat
from functools import lru_cache
from pathlib import Path

from cryptography.fernet import Fernet, InvalidToken
from decouple import config
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured


def _private_key() -> str:
    path = config('PROJECT_ACCESS_CIPHER_KEY_FILE', default='') or (
        Path(settings.PRIVATE_MEDIA_ROOT) / 'runtime-secrets' / 'project-access.key'
    )
    error = (
        'PROJECT_ACCESS_CIPHER_KEY_FILE must be a private, readable regular file '
        'owned by the service user or root.'
    )
    try:
        descriptor = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK)
        with os.fdopen(descriptor, 'rb') as stream:
            metadata = os.fstat(stream.fileno())
            if (
                not stat.S_ISREG(metadata.st_mode)
                or stat.S_IMODE(metadata.st_mode) & 0o077
                or metadata.st_uid not in (0, os.geteuid())
                or metadata.st_nlink != 1
                or metadata.st_size > 128
            ):
                raise ImproperlyConfigured(error)
            return stream.read(129).decode('ascii').strip()
    except FileNotFoundError:
        return ''
    except (OSError, UnicodeError) as exc:
        raise ImproperlyConfigured(error) from exc


def _configured_cipher() -> Fernet:
    key = config('PROJECT_ACCESS_CIPHER_KEY', default='') or _private_key()
    if not key:
        raise ImproperlyConfigured(
            'PROJECT_ACCESS_CIPHER_KEY is not set and no private key file is available. '
            'Restore the existing key '
            'before creating a new one if encrypted data already exists.',
        )
    try:
        return Fernet(key.encode() if isinstance(key, str) else key)
    except (ValueError, TypeError) as exc:
        raise ImproperlyConfigured(
            'PROJECT_ACCESS_CIPHER_KEY is not a valid Fernet key.',
        ) from exc


@lru_cache(maxsize=1)
def _get_cipher() -> Fernet:
    return _configured_cipher()


def cipher_configuration_errors():
    """Validate the current configuration without caching or revealing key material."""
    try:
        _configured_cipher()
    except ImproperlyConfigured as exc:
        return [str(exc)]
    return []


def encrypt_secret(plain: str) -> str:
    """Encrypt a plaintext secret. Empty input returns ''."""
    if not plain:
        return ''
    token = _get_cipher().encrypt(plain.encode('utf-8'))
    return token.decode('ascii')


def decrypt_secret(token: str) -> str:
    """Decrypt a stored secret. Empty or invalid input returns ''."""
    if not token:
        return ''
    try:
        return _get_cipher().decrypt(token.encode('ascii')).decode('utf-8')
    except (InvalidToken, ValueError):
        return ''


def encrypt_password(plain: str) -> str:
    """Backward-compatible password wrapper around :func:`encrypt_secret`."""
    return encrypt_secret(plain)


def decrypt_password(token: str) -> str:
    """Backward-compatible password wrapper around :func:`decrypt_secret`."""
    return decrypt_secret(token)
