# Generated by Django 6.1 on 2026-09-29 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_links', '0002_mcp_viewed_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securelink',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securelink',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secure_links_marked_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securelinkevent',
            name='kind',
            field=models.CharField(choices=[('created', 'Creado'), ('revealed', 'Abierto por el destinatario'), ('reveal_blocked', 'Intento de apertura rechazado'), ('reactivated', 'Reactivado'), ('rotated', 'Enlace regenerado'), ('revoked', 'Revocado'), ('updated', 'Editado'), ('marked_sent', 'Marcado como enviado por el equipo'), ('panel_viewed', 'Contenido visto en el panel'), ('mcp_viewed', 'Contenido consultado desde MCP')], max_length=20),
        ),
    ]
