# Generated by Django 6.1 on 2026-10-01 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_legacy_audience(apps, schema_editor):
    links = apps.get_model('secure_links', 'SecureLink').objects.using(schema_editor.connection.alias)
    links.filter(origin__in=('panel', 'mcp')).update(audience='bearer')
    # No owner inference, token rotation, decryption or payload rewrites.


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_delivery_review_document_evidence'),
        ('secure_links', '0003_securelink_sent_at_securelink_sent_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securelink',
            name='audience',
            field=models.CharField(choices=[('team', 'Equipo de ProjectApp'), ('bearer', 'Destinatario del enlace')], default='team', max_length=10),
        ),
        migrations.AddField(
            model_name='securelink',
            name='creation_request_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(preserve_legacy_audience, migrations.RunPython.noop),
        migrations.AddField(
            model_name='securelink',
            name='creation_request_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securelink',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_secure_links', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='securelink',
            name='replaces',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='secure_links.securelink'),
        ),
        migrations.AlterField(
            model_name='securelink',
            name='origin',
            field=models.CharField(choices=[('panel', 'Equipo (panel)'), ('mcp', 'Asistente (MCP)'), ('public', 'Cliente (página pública)'), ('platform', 'Cliente (Platform)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='securelinkevent',
            name='kind',
            field=models.CharField(choices=[('created', 'Creado'), ('revealed', 'Abierto por el destinatario'), ('reveal_blocked', 'Intento de apertura rechazado'), ('reactivated', 'Reactivado'), ('rotated', 'Enlace regenerado'), ('revoked', 'Revocado'), ('updated', 'Editado'), ('marked_sent', 'Marcado como enviado por el equipo'), ('panel_viewed', 'Contenido visto en el panel'), ('mcp_viewed', 'Contenido consultado desde MCP'), ('replaced', 'Sustituido por otro enlace'), ('url_accessed', 'URL consultada explícitamente')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='securelink',
            index=models.Index(fields=['owner', 'project', 'created_at'], name='secure_link_owner_project'),
        ),
        migrations.AddConstraint(
            model_name='securelink',
            constraint=models.UniqueConstraint(fields=('owner', 'creation_request_id'), name='secure_link_owner_request'),
        ),
    ]
