# Generated by Django 6.1 on 2026-10-06 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_project_data_retention'),
        ('content', '0281_project_data_retention'),
        ('secure_links', '0004_platform_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='securelink',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AlterField(
            model_name='securelink',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secure_links', to='accounts.project'),
        ),
    ]
