# Generated by Django 6.1 on 2026-09-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0264_merge_secure_links_intellectual_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='contract_modality',
            field=models.CharField(choices=[('single', 'Contrato único'), ('split', 'Producto y servicio')], default='single', help_text='How the deal closes: one contract, or a product contract plus a separate hosting, maintenance and support contract. Chosen during negotiation from the Documents tab.', max_length=10),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='service_content_markdown',
            field=models.TextField(blank=True, default='', help_text='Standalone hosting, maintenance and support contract used when the deal closes with two documents. Same placeholders as the main text plus {service_initial_term}, {service_renewal_notice_days} and {service_termination_notice_days}.'),
        ),
        migrations.AlterField(
            model_name='proposaldocument',
            name='document_type',
            field=models.CharField(choices=[('contract', 'Contrato'), ('contract_product', 'Contrato de producto'), ('contract_service', 'Contrato de servicio'), ('amendment', 'Otrosí'), ('legal_annex', 'Anexo legal'), ('client_document', 'Documento del cliente'), ('other', 'Otro')], default='other', max_length=30),
        ),
    ]
