# Generated by Django 6.1 on 2026-09-28 14:28

import content.models.mcp_upload
import content.models.video_resource
import content.video_upload_storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_connectors(apps, schema_editor):
    Connector = apps.get_model('content', 'McpConnector')
    for slug, name in [('partnership-program', 'Programa de Alianza'), ('additional-modules', 'Módulos adicionales')]:
        Connector.objects.get_or_create(slug=slug, defaults={
            'name': name, 'description': f'Administra {name}, sus registros y videos MP4 desde herramientas externas.',
            'is_active': False,
        })


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0269_merge_service_contract_and_proposal_explainer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(seed_connectors, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='mcpupload',
            name='file',
            field=models.FileField(blank=True, storage=content.video_upload_storage.McpUploadStorage(), upload_to=content.models.mcp_upload.mcp_upload_path),
        ),
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=80, unique=True)),
                ('module', models.CharField(max_length=30)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=2)),
                ('mode', models.CharField(choices=[('default', 'Predeterminado'), ('uploaded', 'Cargado'), ('none', 'Sin video')], default='default', max_length=12)),
                ('file', models.FileField(blank=True, storage=content.models.video_resource.video_storage, upload_to=content.models.video_resource.video_resource_path)),
                ('poster', models.FileField(blank=True, storage=content.models.video_resource.video_storage, upload_to=content.models.video_resource.video_resource_path)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('duration_seconds', models.FloatField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalized_video_resource', to='content.businessproposal')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
