# Generated by Django 6.1 on 2026-09-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0270_commercial_video_resources'),
        ('content', '0270_document_folder_authorship'),
    ]

    operations = [
    ]
