# Generated by Django 6.1 on 2026-09-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0273_merge_document_provenance_and_proposal_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='legacy_pricing_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='module_interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='module_interests_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposalchangelog',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resent', 'Resent'), ('expired', 'Expired'), ('duplicated', 'Duplicated'), ('commented', 'Commented'), ('negotiating', 'Negotiating'), ('reengagement', 'Reengagement'), ('call', 'Call'), ('meeting', 'Meeting'), ('followup', 'Follow-up'), ('note', 'Note'), ('calc_confirmed', 'Calculator Confirmed'), ('module_interests', 'Module interests updated'), ('calc_abandoned', 'Calculator Abandoned'), ('auto_archived', 'Auto Archived'), ('status_change', 'Status Change'), ('cond_accepted', 'Conditional Acceptance'), ('calc_followup', 'Calculator Follow-up Sent'), ('req_clicked', 'Requirement Clicked'), ('email_sent', 'Email Sent'), ('seller_inactivity_escalation', 'Seller Inactivity Escalation'), ('platform_launch', 'Platform Launch'), ('stage_warning_sent', 'Stage Warning Sent'), ('stage_overdue_sent', 'Stage Overdue Sent'), ('stage_completed', 'Stage Completed')], max_length=30),
        ),
    ]
