# Generated by Django 6.1 on 2026-10-05 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0278_proposal_project_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='product_content_markdown',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ContractTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('combined', 'combined'), ('product', 'product'), ('service', 'service')], max_length=8)),
                ('version', models.PositiveIntegerField()),
                ('markdown', models.TextField()),
                ('author_label', models.CharField(default='Sistema', max_length=255)),
                ('change_note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mcpcredential')),
                ('restored_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.contracttemplateversion')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='content.contracttemplate')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplateMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('combined', 'combined'), ('product', 'product'), ('service', 'service')], max_length=8)),
                ('pdf_content', models.BinaryField()),
                ('synced_at', models.DateTimeField()),
                ('imported_markdown', models.TextField(blank=True, default='')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract_mirror', to='content.document')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mirrors', to='content.contracttemplate')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.contracttemplateversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contracttemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'variant', 'version'), name='unique_contract_template_revision'),
        ),
        migrations.AddConstraint(
            model_name='contracttemplatemirror',
            constraint=models.UniqueConstraint(fields=('template', 'variant'), name='unique_contract_template_mirror'),
        ),
    ]
