# Generated by Django 6.1 on 2026-10-06 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0280_import_contract_template_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldocument',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProposalContractChangeIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arguments', models.JSONField(default=dict)),
                ('source_hash', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('result', models.JSONField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.businessproposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalContractSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('actor_id_snapshot', models.PositiveBigIntegerField(null=True)),
                ('actor_label', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('change_note', models.TextField(blank=True)),
                ('from_modality', models.CharField(max_length=8)),
                ('to_modality', models.CharField(max_length=8)),
                ('restored_from_id', models.PositiveBigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_snapshots', to='content.businessproposal')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProposalContractSnapshotFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_document_id', models.PositiveBigIntegerField()),
                ('pdf_content', models.BinaryField()),
                ('sha256', models.CharField(max_length=64)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='content.proposalcontractsnapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
