# Generated by Django 6.1 on 2026-10-06 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_userprofile_billing_address'),
        ('content', '0280_import_contract_template_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationfolder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_folders', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='communicationthread',
            name='managed_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_root_thread', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='communicationthread',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_threads', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='documentfolder',
            name='managed_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_root_folder', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='documentfolder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_folders', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='documentstateepisode',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state_episodes', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='financingagreement',
            name='source_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financing_agreements', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='hostingrecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hosting_records', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='incomerecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_records', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='linktree',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linktrees', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='projectbrandasset',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brand_assets', to='accounts.project'),
        ),
        migrations.CreateModel(
            name='ProjectRetentionContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_project_id', models.PositiveBigIntegerField(unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('retained_records', models.JSONField(default=dict)),
                ('category_counts', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='communicationfolder',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='communicationthread',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='document',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='documentstateepisode',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='financingagreement',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='hostingrecord',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='linktree',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AddField(
            model_name='projectbrandasset',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
    ]
