# Generated by Django 6.1.2 on 2026-10-07 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0282_merge_contract_snapshots_project_retention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalProjectReassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('source_project_id', models.PositiveBigIntegerField()),
                ('target_project_id', models.PositiveBigIntegerField()),
                ('reason', models.TextField()),
                ('impact', models.JSONField()),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_reassignments', to='content.businessproposal')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
