# Generated by Django 6.1.2 on 2026-10-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0284_platform_manager_metadata'),
        ('content', '0284_project_retention_operation'),
    ]

    operations = [
    ]
