# Generated by Django 6.1.2 on 2026-10-09 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0285_merge_platform_manager_retention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIntegrityOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('apply', 'Corrección'), ('undo', 'Deshacer una corrección')], max_length=8)),
                ('source', models.CharField(max_length=64)),
                ('catalog_version', models.CharField(max_length=20)),
                ('scope', models.JSONField(default=dict)),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('impact_hash', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('steps', models.JSONField(default=list)),
                ('history_operation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reverts', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reverted_by', to='content.dataintegrityoperation')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
