# Generated by Django 6.1.2 on 2026-10-09 22:55

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


def backfill_mirror_folder(apps, schema_editor):
    template_model = apps.get_model('content', 'ContractTemplate')
    mirror_model = apps.get_model('content', 'ContractTemplateMirror')
    database = schema_editor.connection.alias
    for template in template_model.objects.using(database).select_related('mirror_document').iterator():
        folder_ids = set(mirror_model.objects.using(database).filter(
            template_id=template.pk, document__folder_id__isnull=False,
        ).values_list('document__folder_id', flat=True))
        if template.mirror_document_id and template.mirror_document.folder_id is not None:
            folder_ids.add(template.mirror_document.folder_id)
        if len(folder_ids) == 1:
            template_model.objects.using(database).filter(pk=template.pk).update(mirror_folder_id=folder_ids.pop())


class Migration(migrations.Migration):

    dependencies: ClassVar = [
        ('content', '0285_merge_platform_manager_retention'),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name='contracttemplate',
            name='mirror_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.documentfolder'),
        ),
        migrations.RunPython(backfill_mirror_folder, migrations.RunPython.noop),
    ]
