# Generated by Django 6.1.2 on 2026-10-09 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Historical seed: keep the complete copy here, independent of application code.
PROGRAM_V1 = {
    'es': {
        'seo': {
            'title': 'Building with Us | ProjectApp',
            'description': 'Construye un producto con ProjectApp: tu experiencia en la industria y nuestra cadena de producción se unen para resolver problemas con impacto económico.',
        },
        'hero': {
            'eyebrow': 'Building with Us',
            'title': 'Construye con nosotros. Construimos para ti.',
            'subtitle': 'Tú conoces el problema de tu industria. Nosotros aportamos toda la cadena de producción para convertirlo en un producto que genere ingresos.',
            'note': 'Una alianza para expertos de negocio con un problema concreto por resolver.',
        },
        'origin': {
            'title': 'Las mejores ideas nacen de conocer el problema',
            'summary': 'Cada industria tiene problemas que solo reconoce quien los vive. Muchas tareas manuales y repetitivas pueden convertirse en productos. Una casa de software no vive todas esas industrias: por eso buscamos tu experiencia.',
            'industries': ['Creadores de contenido', 'Sector legal', 'Retail', 'Cannabis', 'Cualquier industria'],
            'points': [
                'Identifica un problema concreto que se repite en tu operación.',
                'Explica a quién le duele y qué impacto económico tiene.',
                'Aporta el conocimiento que permite decidir qué construir.',
                'Trabajemos juntos para convertir esa solución en un producto vendible.',
            ],
        },
        'contribution': {
            'title': 'ProjectApp aporta toda la cadena de producción',
            'summary': 'Nos encargamos de llevar la idea desde los requerimientos hasta la operación en producción, con responsables y entregables definidos.',
            'items': [
                {'id': 'requirements', 'title': 'Levantamiento de requerimientos', 'summary': 'Traducimos el problema y tus decisiones de negocio en requisitos verificables.'},
                {'id': 'design', 'title': 'Diseño de la aplicación', 'summary': 'Diseñamos los recorridos y la solución para las personas que la van a usar.'},
                {'id': 'development', 'title': 'Desarrollo', 'summary': 'Construimos el producto de acuerdo con el alcance aprobado.'},
                {'id': 'implementation', 'title': 'Implementación', 'summary': 'Integramos la solución con la operación definida para el producto.'},
                {'id': 'delivery', 'title': 'Entrega', 'summary': 'Presentamos los avances con criterios de aceptación y evidencia.'},
                {'id': 'launch', 'title': 'Puesta en marcha', 'summary': 'Preparamos el lanzamiento y acompañamos la entrada de los primeros usuarios.'},
                {'id': 'operation', 'title': 'Operación en producción', 'summary': 'Aportamos hosting, mantenimiento y soporte según las condiciones de la alianza.'},
            ],
        },
        'expert_profile': {
            'title': 'Tu experiencia hace que el producto tenga sentido',
            'summary': 'Buscamos un experto de negocio con una idea concreta, un problema por resolver y disposición para participar activamente.',
            'items': [
                {'id': 'industry', 'title': 'Conocimiento de la industria', 'summary': 'Conoces el problema de primera mano y puedes explicar cómo afecta a sus usuarios.'},
                {'id': 'economic-impact', 'title': 'Propósito económico', 'summary': 'Resolver el problema debe crear un impacto monetizable y una oportunidad comercial real.'},
                {'id': 'decisions', 'title': 'Disponibilidad para decidir y validar', 'summary': 'Dedicas tiempo a resolver dudas, priorizar y validar la calidad con criterio de negocio.'},
                {'id': 'sales', 'title': 'Compromiso para vender', 'summary': 'Te involucras en acercar el producto a sus usuarios e inviertes en su estrategia de ventas.'},
            ],
        },
        'participation_models': {
            'title': 'Tres formas de construir la alianza',
            'summary': 'La participación de cada parte depende del modelo elegido y se acuerda en el contrato. Tu compromiso se convierte en responsabilidades y hitos verificables.',
            'items': [
                {
                    'id': 'monthly-investment', 'name': 'Con inversión mensual', 'badge': 'Aporte durante la incubación',
                    'summary': 'Aportas una cuota mensual durante el periodo de incubación. ProjectApp aporta la cadena de producción y juntos validamos el producto.',
                    'ideal_for': 'Expertos que pueden sostener una inversión mensual mientras se construye la solución.',
                    'expert_contributes': ['Una cuota mensual durante la incubación.', 'Decisiones y validación del negocio.', 'Compromiso con la venta del producto.'],
                    'projectapp_contributes': ['Toda la cadena de producción del producto.', 'Hosting, mantenimiento y soporte acordados.', 'Seguimiento del alcance y los hitos.'],
                },
                {
                    'id': 'validation', 'name': 'Con validación', 'badge': 'Criterio y dedicación',
                    'summary': 'No haces un aporte monetario al desarrollo. Asumes el control de calidad y la validación con criterio, hasta llevar la aplicación a un producto mínimo viable que las personas puedan usar.',
                    'ideal_for': 'Expertos con disponibilidad para probar, validar y acompañar a usuarios reales.',
                    'expert_contributes': ['Control de calidad y validación con criterio de negocio.', 'Dedicación para llevar el producto a un MVP usable.', 'Compromiso e inversión en ventas.'],
                    'projectapp_contributes': ['Toda la cadena de producción del producto.', 'Hosting, mantenimiento y soporte acordados.', 'Correcciones dentro del alcance validado.'],
                },
                {
                    'id': 'commercial-investment', 'name': 'Con inversión comercial', 'badge': 'Marketing y ventas',
                    'summary': 'En lugar de invertir en desarrollo, comprometes dinero a marketing y a la estrategia de ventas durante un periodo razonable acordado en el contrato.',
                    'ideal_for': 'Expertos preparados para impulsar la llegada del producto al mercado.',
                    'expert_contributes': ['Inversión en marketing y estrategia de ventas.', 'Ejecución comercial durante el periodo acordado.', 'Decisiones y validación del negocio.'],
                    'projectapp_contributes': ['Toda la cadena de producción del producto.', 'Hosting, mantenimiento y soporte acordados.', 'Un producto listo para la puesta en marcha acordada.'],
                },
            ],
        },
        'incubation_periods': {
            'title': 'Un periodo de incubación acorde al alcance',
            'summary': 'Elegimos un horizonte concreto según la complejidad del problema y los objetivos de la alianza.',
            'items': [
                {'id': 'three-months', 'months': 3, 'title': 'Tres meses', 'summary': 'Para una solución acotada que necesita validar pronto su uso principal.'},
                {'id': 'six-months', 'months': 6, 'title': 'Seis meses', 'summary': 'Para un producto con varios recorridos que requieren validación progresiva.'},
                {'id': 'nine-months', 'months': 9, 'title': 'Nueve meses', 'summary': 'Para procesos e integraciones que necesitan más etapas de implementación.'},
                {'id': 'twelve-months', 'months': 12, 'title': 'Un año', 'summary': 'Para un alcance más amplio con objetivos y entregas delimitados desde el inicio.'},
            ],
        },
        'scope': {
            'title': 'Objetivos claros, alcance definido',
            'summary': 'La alianza tiene un comienzo, entregables y criterios de cierre. Construimos un producto con límites acordados para evitar un proyecto infinito.',
            'items': [
                {'id': 'objectives', 'title': 'Objetivos verificables', 'summary': 'Definimos qué problema se resuelve, para quién y qué resultado buscamos.'},
                {'id': 'baseline', 'title': 'Una línea base compartida', 'summary': 'Cada requerimiento tiene un criterio de aceptación, evidencia esperada y un responsable.'},
                {'id': 'changes', 'title': 'Control de cambios', 'summary': 'Los cambios se evalúan por su impacto y se acuerdan antes de ampliar el trabajo.'},
                {'id': 'stages', 'title': 'Etapas con propósito', 'summary': 'Avanzamos por implementación, validación y estabilización del alcance aprobado.'},
            ],
        },
        'milestones': {
            'title': 'La participación se gana con hitos',
            'summary': 'El compromiso se demuestra con resultados. Estos hitos de referencia ayudan a organizar el avance y la participación de la alianza.',
            'items': [
                {'id': 'kickoff', 'title': 'Alcance aprobado e inicio registrado', 'summary': 'Acordamos la línea base y dejamos un acta de inicio con responsabilidades.'},
                {'id': 'first-version', 'title': 'Primera versión validada', 'summary': 'Comprobamos con evidencia que la primera solución responde al problema.'},
                {'id': 'production-mvp', 'title': 'MVP en producción con usuarios reales', 'summary': 'Llevamos una versión usable a producción y validamos su uso en la práctica.'},
                {'id': 'commercial-goal', 'title': 'Objetivo comercial acordado', 'summary': 'Verificamos el resultado de ventas definido para la alianza.'},
            ],
            'note': 'Cada alianza define sus propios hitos y las condiciones de participación en el contrato.',
        },
        'agreement': {
            'title': 'Una alianza respaldada por un contrato',
            'summary': 'Las responsabilidades y los resultados esperados se acuerdan por escrito antes de iniciar. El contrato gobierna la participación y el futuro del producto.',
            'items': [
                {'id': 'earned-participation', 'title': 'Participación por hitos', 'summary': 'La participación se adquiere al cumplir los hitos y compromisos acordados.'},
                {'id': 'commitment', 'title': 'Compromiso con consecuencias claras', 'summary': 'Si no cumples el compromiso esperado, pierdes tu participación y esta permanece en ProjectApp, según el contrato.'},
                {'id': 'success', 'title': 'Participación al alcanzar el éxito', 'summary': 'Si el proyecto tiene éxito y cumples las condiciones pactadas, conservas tu participación.'},
                {'id': 'sales-investment', 'title': 'Inversión en ventas', 'summary': 'También inviertes dinero en ventas y asumes las responsabilidades comerciales pactadas.'},
                {'id': 'ownership-and-exit', 'title': 'Propiedad, operación y salida', 'summary': 'Definimos por escrito la propiedad del producto, su operación y las condiciones de salida de la alianza.'},
            ],
        },
        'process': {
            'title': 'Así comienza Building with Us',
            'items': [
                {'id': 'conversation', 'title': 'Conversación', 'summary': 'Cuéntanos el problema y tu experiencia en la industria.'},
                {'id': 'evaluation', 'title': 'Evaluación de la idea', 'summary': 'Revisamos su impacto económico, viabilidad y oportunidad comercial.'},
                {'id': 'scope', 'title': 'Definición del alcance', 'summary': 'Acordamos objetivos, entregables, periodo de incubación y responsabilidades.'},
                {'id': 'contract', 'title': 'Contrato', 'summary': 'Formalizamos el modelo, los hitos y las condiciones de la alianza.'},
                {'id': 'kickoff', 'title': 'Inicio', 'summary': 'Registramos el acuerdo de inicio y comenzamos a construir.'},
            ],
        },
        'faq': {
            'title': 'Preguntas frecuentes',
            'items': [
                {'id': 'technology', 'question': '¿Necesito saber de tecnología?', 'answer': 'No. Tú aportas el conocimiento del negocio y ProjectApp aporta la cadena de producción. Sí necesitas disponibilidad para decidir y validar.'},
                {'id': 'ideas', 'question': '¿Qué tipo de ideas buscamos?', 'answer': 'Ideas concretas que resuelvan un problema real de una industria y creen un impacto económico que pueda convertirse en ingresos.'},
                {'id': 'start', 'question': '¿Cómo empieza la alianza?', 'answer': 'Con una conversación y una evaluación de la idea. Si hay una oportunidad, definimos el alcance y firmamos el contrato antes de iniciar.'},
                {'id': 'cost', 'question': '¿Cuánto cuesta participar?', 'answer': 'Depende del modelo elegido y del alcance. Los aportes y condiciones de cada parte se acuerdan en el contrato.'},
                {'id': 'industry', 'question': '¿Puedo traer una idea de cualquier industria?', 'answer': 'Sí. Lo importante es que conozcas el problema, puedas demostrar su impacto y te comprometas con la validación y la venta del producto.'},
                {'id': 'stopped-project', 'question': '¿Qué pasa si el proyecto no avanza?', 'answer': 'El contrato define qué sucede con el incumplimiento de compromisos, la participación y la salida. Si no cumples el compromiso esperado, tu participación permanece en ProjectApp.'},
            ],
        },
        'cta': {
            'title': 'Cuéntanos el problema que quieres resolver',
            'body': 'Conversemos sobre tu industria, la oportunidad y cómo podríamos construir el producto juntos.',
            'button_label': 'Hablar por WhatsApp',
            'whatsapp_message': 'Hola, ProjectApp. Quiero conocer Building with Us y conversar sobre un problema de mi industria que podría convertirse en un producto.',
        },
        'legal': {
            'disclaimer': 'Este contenido es informativo y no constituye una oferta vinculante. La participación está sujeta a la evaluación de la idea y a la firma del contrato de la alianza.',
        },
    },
    'en': {
        'seo': {
            'title': 'Building with Us | ProjectApp',
            'description': 'Build a product with ProjectApp. Combine your industry expertise with our full production capabilities to solve problems with real economic impact.',
        },
        'hero': {
            'eyebrow': 'Building with Us',
            'title': 'Build with us. We build for you.',
            'subtitle': 'You know the problem in your industry. We bring the entire production chain to turn it into a product that generates revenue.',
            'note': 'An alliance for business experts with a specific problem to solve.',
        },
        'origin': {
            'title': 'Great ideas start with understanding the problem',
            'summary': 'Every industry has problems that only insiders truly understand. Manual, repetitive work can become a product opportunity. A software house cannot live every industry firsthand: that is where your expertise comes in.',
            'industries': ['Content creators', 'Legal sector', 'Retail', 'Cannabis', 'Any industry'],
            'points': [
                'Identify a specific problem that keeps coming up in your work.',
                'Explain who experiences it and its economic impact.',
                'Bring the knowledge that guides what we should build.',
                'Work with us to turn the solution into a product people will buy.',
            ],
        },
        'contribution': {
            'title': 'ProjectApp brings the entire production chain',
            'summary': 'We take the idea from requirements to production operations, with clear deliverables and responsibilities.',
            'items': [
                {'id': 'requirements', 'title': 'Requirements gathering', 'summary': 'We turn the problem and your business decisions into testable requirements.'},
                {'id': 'design', 'title': 'Application design', 'summary': 'We design the experience and solution around the people who will use it.'},
                {'id': 'development', 'title': 'Development', 'summary': 'We build the product within the approved scope.'},
                {'id': 'implementation', 'title': 'Implementation', 'summary': 'We integrate the solution into the operations defined for the product.'},
                {'id': 'delivery', 'title': 'Delivery', 'summary': 'We present progress against acceptance criteria, supported by evidence.'},
                {'id': 'launch', 'title': 'Launch', 'summary': 'We prepare the launch and support the first users as they get started.'},
                {'id': 'operation', 'title': 'Production operations', 'summary': 'We provide hosting, maintenance and support under the terms of the alliance.'},
            ],
        },
        'expert_profile': {
            'title': 'Your expertise gives the product direction',
            'summary': 'We look for a business expert with a concrete idea, a problem to solve and a willingness to take an active role.',
            'items': [
                {'id': 'industry', 'title': 'Industry knowledge', 'summary': 'You know the problem firsthand and can explain how it affects the people involved.'},
                {'id': 'economic-impact', 'title': 'Economic purpose', 'summary': 'Solving the problem must create monetizable impact and a real business opportunity.'},
                {'id': 'decisions', 'title': 'Time to decide and validate', 'summary': 'You make time to answer questions, set priorities and assess quality with business judgment.'},
                {'id': 'sales', 'title': 'Commitment to sales', 'summary': 'You help reach the right users and invest in the product’s sales strategy.'},
            ],
        },
        'participation_models': {
            'title': 'Three ways to build the alliance',
            'summary': 'Each party’s participation depends on the chosen model and is agreed in the contract. Your commitment becomes clear responsibilities and measurable milestones.',
            'items': [
                {
                    'id': 'monthly-investment', 'name': 'Monthly investment', 'badge': 'Support during incubation',
                    'summary': 'You contribute a monthly fee throughout the incubation period. ProjectApp provides the production chain, and we validate the product together.',
                    'ideal_for': 'Experts who can sustain a monthly investment while the solution is being built.',
                    'expert_contributes': ['A monthly fee during incubation.', 'Business decisions and validation.', 'Commitment to selling the product.'],
                    'projectapp_contributes': ['The product’s entire production chain.', 'Agreed hosting, maintenance and support.', 'Scope and milestone tracking.'],
                },
                {
                    'id': 'validation', 'name': 'Validation', 'badge': 'Judgment and dedication',
                    'summary': 'You make no monetary contribution to development. You own quality control and thoughtful validation, taking the application to a minimum viable product that people can actually use.',
                    'ideal_for': 'Experts with time to test, validate and work with real users.',
                    'expert_contributes': ['Quality control and validation guided by business judgment.', 'The dedication to reach a usable MVP.', 'Commitment and investment in sales.'],
                    'projectapp_contributes': ['The product’s entire production chain.', 'Agreed hosting, maintenance and support.', 'Corrections within the validated scope.'],
                },
                {
                    'id': 'commercial-investment', 'name': 'Commercial investment', 'badge': 'Marketing and sales',
                    'summary': 'Instead of investing in development, you commit money to marketing and the sales strategy for a reasonable period agreed in the contract.',
                    'ideal_for': 'Experts ready to drive the product’s market entry.',
                    'expert_contributes': ['Investment in marketing and the sales strategy.', 'Commercial execution over the agreed period.', 'Business decisions and validation.'],
                    'projectapp_contributes': ['The product’s entire production chain.', 'Agreed hosting, maintenance and support.', 'A product ready for the agreed launch.'],
                },
            ],
        },
        'incubation_periods': {
            'title': 'An incubation period that fits the scope',
            'summary': 'We choose a defined timeframe based on the problem’s complexity and the alliance’s objectives.',
            'items': [
                {'id': 'three-months', 'months': 3, 'title': 'Three months', 'summary': 'For a focused solution that needs early validation of its main use case.'},
                {'id': 'six-months', 'months': 6, 'title': 'Six months', 'summary': 'For a product with several user journeys that need progressive validation.'},
                {'id': 'nine-months', 'months': 9, 'title': 'Nine months', 'summary': 'For workflows and integrations that require more implementation stages.'},
                {'id': 'twelve-months', 'months': 12, 'title': 'One year', 'summary': 'For a broader scope with objectives and deliveries defined from the start.'},
            ],
        },
        'scope': {
            'title': 'Clear objectives and a defined scope',
            'summary': 'The alliance has a starting point, deliverables and completion criteria. We agree on boundaries so the product does not become an endless project.',
            'items': [
                {'id': 'objectives', 'title': 'Verifiable objectives', 'summary': 'We define the problem, who we solve it for and the outcome we want to achieve.'},
                {'id': 'baseline', 'title': 'A shared baseline', 'summary': 'Each requirement has an acceptance criterion, expected evidence and an owner.'},
                {'id': 'changes', 'title': 'Change control', 'summary': 'We assess the impact of changes and agree on them before extending the work.'},
                {'id': 'stages', 'title': 'Purposeful stages', 'summary': 'We move through implementation, validation and stabilization of the approved scope.'},
            ],
        },
        'milestones': {
            'title': 'Participation is earned through milestones',
            'summary': 'Commitment is demonstrated through results. These reference milestones help organize progress and participation in the alliance.',
            'items': [
                {'id': 'kickoff', 'title': 'Approved scope and recorded kickoff', 'summary': 'We agree on the baseline and record the kickoff and responsibilities.'},
                {'id': 'first-version', 'title': 'First validated version', 'summary': 'We use evidence to check that the initial solution addresses the problem.'},
                {'id': 'production-mvp', 'title': 'Production MVP with real users', 'summary': 'We launch a usable version and validate how it works in practice.'},
                {'id': 'commercial-goal', 'title': 'Agreed commercial goal', 'summary': 'We verify the sales outcome defined for the alliance.'},
            ],
            'note': 'Each alliance defines its milestones and participation terms in the contract.',
        },
        'agreement': {
            'title': 'An alliance backed by a contract',
            'summary': 'Responsibilities and expected outcomes are agreed in writing before work begins. The contract governs participation and the product’s future.',
            'items': [
                {'id': 'earned-participation', 'title': 'Milestone-based participation', 'summary': 'Participation is earned by meeting the agreed milestones and commitments.'},
                {'id': 'commitment', 'title': 'Commitment with clear consequences', 'summary': 'If you do not meet the expected commitment, you lose your participation and it remains with ProjectApp, as governed by the contract.'},
                {'id': 'success', 'title': 'Participation when the project succeeds', 'summary': 'If the project succeeds and you fulfill the agreed conditions, you retain your participation.'},
                {'id': 'sales-investment', 'title': 'Investment in sales', 'summary': 'You also invest money in sales and take on the agreed commercial responsibilities.'},
                {'id': 'ownership-and-exit', 'title': 'Ownership, operations and exit', 'summary': 'We agree in writing on product ownership, ongoing operations and how either party may leave the alliance.'},
            ],
        },
        'process': {
            'title': 'How Building with Us begins',
            'items': [
                {'id': 'conversation', 'title': 'Conversation', 'summary': 'Tell us about the problem and your industry experience.'},
                {'id': 'evaluation', 'title': 'Idea evaluation', 'summary': 'We review the economic impact, feasibility and business opportunity.'},
                {'id': 'scope', 'title': 'Scope definition', 'summary': 'We agree on objectives, deliverables, the incubation period and responsibilities.'},
                {'id': 'contract', 'title': 'Contract', 'summary': 'We formalize the model, milestones and terms of the alliance.'},
                {'id': 'kickoff', 'title': 'Kickoff', 'summary': 'We record the kickoff agreement and start building.'},
            ],
        },
        'faq': {
            'title': 'Frequently asked questions',
            'items': [
                {'id': 'technology', 'question': 'Do I need technical knowledge?', 'answer': 'No. You bring the business expertise and ProjectApp provides the production chain. You do need time to make decisions and validate the product.'},
                {'id': 'ideas', 'question': 'What kinds of ideas are a good fit?', 'answer': 'Concrete ideas that solve a real industry problem and create economic impact that can become revenue.'},
                {'id': 'start', 'question': 'How does the alliance start?', 'answer': 'We begin with a conversation and an evaluation of the idea. If there is an opportunity, we define the scope and sign the contract before starting work.'},
                {'id': 'cost', 'question': 'How much does participation cost?', 'answer': 'It depends on the chosen model and scope. Each party’s contributions and terms are agreed in the contract.'},
                {'id': 'industry', 'question': 'Can I bring an idea from any industry?', 'answer': 'Yes. What matters is that you know the problem, can demonstrate its impact and are committed to validating and selling the product.'},
                {'id': 'stopped-project', 'question': 'What happens if the project does not move forward?', 'answer': 'The contract governs unmet commitments, participation and exit. If you do not meet the expected commitment, your participation remains with ProjectApp.'},
            ],
        },
        'cta': {
            'title': 'Tell us about the problem you want to solve',
            'body': 'Let’s talk about your industry, the opportunity and how we could build the product together.',
            'button_label': 'Chat on WhatsApp',
            'whatsapp_message': 'Hi, ProjectApp. I would like to learn about Building with Us and discuss an industry problem that could become a product.',
        },
        'legal': {
            'disclaimer': 'This content is for information only and is not a binding offer. Participation is subject to evaluation of the idea and signing the alliance contract.',
        },
    },
}


def seed_program(apps, schema_editor):
    Program = apps.get_model('content', 'BuildingWithUsProgram')
    Revision = apps.get_model('content', 'BuildingWithUsProgramRevision')
    Connector = apps.get_model('content', 'McpConnector')
    alias = schema_editor.connection.alias
    if not Program.objects.using(alias).exists():
        revision = Revision.objects.using(alias).create(
            version=1, content=PROGRAM_V1, author_label='Sistema',
            change_note='Versión inicial de la presentación Building with Us (PA-174).',
        )
        Program.objects.using(alias).create(pk=1, current_revision=revision)
    Connector.objects.using(alias).get_or_create(slug='building-with-us', defaults={
        'name': 'Building with Us',
        'description': 'Administra Building with Us: la presentación versionada y el contrato de la alianza.',
        'is_active': False,
    })


def reverse_seed(apps, schema_editor):
    Connector = apps.get_model('content', 'McpConnector')
    Connector.objects.using(schema_editor.connection.alias).filter(
        slug='building-with-us', credentials__isnull=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0285_merge_platform_manager_retention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingWithUsProgramRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('author_label', models.CharField(default='Sistema', max_length=255)),
                ('change_note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.JSONField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mcpcredential')),
                ('restored_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.buildingwithusprogramrevision')),
            ],
            options={
                'ordering': ['-version'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuildingWithUsProgram',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.buildingwithusprogramrevision')),
            ],
        ),
        migrations.AddConstraint(
            model_name='buildingwithusprogramrevision',
            constraint=models.UniqueConstraint(fields=('version',), name='content_buildingwithusprogramrevision_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='buildingwithusprogram',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='building_with_us_program_singleton'),
        ),
        migrations.RunPython(seed_program, reverse_seed),
    ]
