# Generated by Django 6.1.2 on 2026-10-10 00:44

from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar = [
        ('content', '0286_contracttemplate_mirror_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name='DocumentOwnershipOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('migration', 'Migración'), ('adoption', 'Adopción'), ('undo', 'Deshacer')], max_length=12)),
                ('origin', models.CharField(choices=[('mcp', 'MCP'), ('panel', 'Panel'), ('auto', 'Automática')], max_length=8)),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('plan_hash', models.CharField(max_length=64)),
                ('input', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('items', models.JSONField(default=list)),
                ('created_folder_ids', models.JSONField(default=list)),
                ('deleted_folder_snapshots', models.JSONField(default=list)),
                ('created_project_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('report', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.mcpcredential')),
                ('reverts', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reverted_by', to='content.documentownershipoperation')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
