# Generated by Django 6.1.2 on 2026-10-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0286_data_integrity_operation'),
        ('content', '0286_seed_government_procurement_module'),
    ]

    operations = [
    ]
