# Generated by Django 6.1.2 on 2026-10-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0287_building_with_us_contract'),
        ('content', '0287_merge_20261010_0646'),
    ]

    operations = [
    ]
