# Generated by Django 6.1.2 on 2026-10-10 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0289_merge_20261010_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCompletionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('skipped', 'Omitido')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('income', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_notice', to='content.incomerecord')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='income_notice_pending_idx')],
            },
        ),
    ]
