"""Shrink-only backlogs for the MCP input-schema policy.

Generic adapters retain a server-validated Panel payload until an explicit
schema is ready; their root argument descriptions are also deferred.
Undescribed arguments track strict tools whose root
properties still need prose. Deferred schemas belong to other in-flight
changes and temporarily skip structural and description auditing.

Remove entries as their contracts improve; do not add entries or raise the
test ceilings to accommodate new debt. Registry-derived tests reject stale
names, stale exemptions and growth beyond the initial sizes.
"""

GENERIC_ADAPTER_BACKLOG = frozenset({
    # accounting-billing
    'bulk_assign_hosting_client',
    'bulk_assign_hosting_project',
    'cancel_collection_account',
    'create_collection_account',
    'create_hosting_cycle',
    'delete_collection_account_draft',
    'delete_hosting_cycle',
    'download_collection_account_pdf',
    'get_accounting_settings_full',
    'get_collection_account',
    'get_collection_account_next_number',
    'list_accounting_email_logs',
    'list_collection_accounts',
    'list_hosting_cycles',
    'mark_collection_account_paid',
    'preview_collection_account',
    'read_accounting_email_body',
    'resend_collection_account',
    'retry_accounting_email',
    'update_accounting_settings_full',
    # accounting-cards
    'create_credit_card',
    'create_merchant_alias',
    'create_statement_transaction_batch',
    'delete_credit_card',
    'delete_statement_pdf',
    'delete_statement_transaction',
    'get_credit_card',
    'learn_merchant_alias',
    'list_credit_cards',
    'resolve_merchant_aliases',
    'update_credit_card',
    'upload_statement_pdf',
    # accounting-ledger
    'bulk_assign_income_client',
    'bulk_assign_income_project',
    'create_recurring_category',
    'delete_recurring_category',
    'duplicate_income_draft',
    'export_accounting_records',
    'export_accounting_workbook',
    'get_accounting_history_counts',
    'get_accounting_stats',
    'list_accounting_change_logs',
    'list_recurring_categories',
    'reorder_recurring_categories',
    'reorder_recurring_payments',
    'suggest_income_period',
    'update_recurring_category',
    # additional-modules
    'create_additional_module',
    'create_additional_module_category',
    'create_additional_module_share',
    'get_additional_modules_catalog',
    'list_additional_module_shares',
    'render_additional_modules_pdf',
    'reorder_additional_modules',
    'set_additional_module_category_status',
    'set_additional_module_share_status',
    'set_additional_module_status',
    'update_additional_module',
    'update_additional_module_category',
    'update_additional_module_share',
    # commercial
    'archive_client',
    'bulk_action_diagnostics',
    'complete_proposal_stage',
    'create_diagnostic_activity',
    'create_hour_package',
    'create_partnership_agreement',
    'delete_diagnostic_attachment',
    'delete_hour_package',
    'delete_proposal_document',
    'delete_proposal_section',
    'download_partnership_signed_pdf',
    'download_proposal_approval_file',
    'download_proposal_document',
    'export_proposal_analytics_csv',
    'export_proposal_json',
    'generate_diagnostic_confidentiality',
    'get_branded_email_defaults',
    'get_client_status_counts',
    'get_diagnostic_analytics',
    'get_diagnostic_defaults',
    'get_diagnostic_email_defaults',
    'get_diagnostic_scorecard',
    'get_email_deliverability',
    'get_email_template',
    'get_explainer_video_settings',
    'get_financing_program',
    'get_hour_package',
    'get_hour_package_settings',
    'get_partnership_agreement',
    'get_partnership_client_context',
    'get_partnership_settings',
    'get_proposal_analytics',
    'get_proposal_approval',
    'get_proposal_company_settings',
    'get_proposal_dashboard',
    'get_proposal_defaults',
    'get_proposal_email_defaults',
    'get_proposal_formalization_options',
    'get_proposal_scorecard',
    'list_branded_emails',
    'list_client_emails',
    'list_diagnostic_activity',
    'list_diagnostic_attachments',
    'list_diagnostic_emails',
    'list_email_templates',
    'list_hour_packages',
    'list_partnership_agreements',
    'list_partnership_templates',
    'list_proposal_activity',
    'list_proposal_alerts',
    'list_proposal_documents',
    'list_proposal_emails',
    'preview_client_archive',
    'preview_email_template',
    'preview_proposal_email',
    'preview_proposal_project_reassignment',
    'publish_partnership_policy',
    'read_client_email_body',
    'read_proposal_contract_markdown',
    'read_proposal_document_markdown',
    'read_proposal_formalization_markdown',
    'render_diagnostic_confidentiality_pdf',
    'render_diagnostic_draft_confidentiality_pdf',
    'render_financing_program_pdf',
    'render_partnership_agreement_pdf',
    'render_proposal_contract_pdf',
    'render_proposal_draft_contract_pdf',
    'render_proposal_formalization_pdf',
    'reset_diagnostic_defaults',
    'reset_diagnostic_section',
    'reset_email_template',
    'restore_default_hour_packages',
    'retry_client_email',
    'retry_proposal_first_view_notification',
    'send_diagnostic_attachments',
    'send_diagnostic_email',
    'send_proposal_discount_offer',
    'toggle_proposal_active',
    'transition_partnership_agreement',
    'unarchive_client',
    'update_diagnostic_confidentiality',
    'update_diagnostic_defaults',
    'update_explainer_video_settings',
    'update_hour_package',
    'update_hour_package_settings',
    'update_partnership_agreement',
    'upload_diagnostic_attachment',
    'upload_partnership_signed_pdf',
    # communications
    'create_email_copy_recipient',
    'delete_email_copy_recipient',
    'download_email_attachment',
    'get_email_defaults',
    'list_email_copy_recipients',
    'list_email_history',
    'preview_email',
    'read_email_body',
    'resend_email',
    'send_email',
    'update_email_copy_recipient',
    'update_email_defaults',
    # content
    'create_linktree',
    'create_portfolio_from_json',
    'create_portfolio_work',
    'create_qr_card',
    'delete_linktree',
    'delete_portfolio_work',
    'delete_qr_card',
    'duplicate_blog_post',
    'duplicate_portfolio_work',
    'get_linktree',
    'get_portfolio_template',
    'get_portfolio_work',
    'list_linktrees',
    'list_portfolio_works',
    'list_qr_cards',
    'publish_blog_to_linkedin',
    'remove_linktree_logo',
    'update_linktree',
    'update_portfolio_work',
    'update_qr_card',
    'upload_blog_cover',
    'upload_linktree_avatar',
    'upload_linktree_logo',
    'upload_portfolio_cover',
    # operations
    'get_operations_dashboard',
})

UNDESCRIBED_ARGUMENT_BACKLOG = frozenset({
    # accounting-billing
    'create_hosting',
    'create_notification_recipient',
    'list_hosting',
    'list_notification_recipient',
    'send_hosting_collection_account',
    'update_hosting',
    'update_notification_recipient',
    'update_settings',
    # accounting-cards
    'create_card_snapshot',
    'create_statement',
    'delete_merchant_alias',
    'delete_statement',
    'finalize_statement',
    'get_statement',
    'get_statement_status',
    'list_card_snapshot',
    'list_merchant_aliases',
    'list_statements',
    'reopen_statement',
    'resolve_merchants',
    'save_merchant_aliases',
    'update_card_snapshot',
    'update_merchant_alias',
    'update_statement',
    'update_statement_transaction',
    # accounting-ledger
    'bulk_action_recurring',
    'create_ads',
    'create_expense',
    'create_income',
    'create_pocket',
    'create_recurring',
    'get_dashboard',
    'list_ads',
    'list_change_logs',
    'list_expense',
    'list_income',
    'list_pocket',
    'list_recurring',
    'mute_income',
    'mute_recurring',
    'set_recurring_active',
    'settle_income',
    'update_ads',
    'update_expense',
    'update_income',
    'update_pocket',
    'update_recurring',
    # additional-modules
    'get_additional_modules_video',
    'remove_additional_modules_video',
    'restore_default_additional_modules_video',
    'set_additional_modules_video',
    'set_additional_modules_video_visibility',
    # commercial
    'apply_proposal_section_sync',
    'bulk_action_proposals',
    'bulk_update_diagnostic_sections',
    'create_client',
    'create_diagnostic',
    'create_proposal',
    'create_proposal_alert',
    'create_proposal_section',
    'create_share_link',
    'dismiss_proposal_alert',
    'download_proposal_formalization_file',
    'get_diagnostic_template',
    'get_partnership_program_video',
    'get_proposal_contract_template',
    'get_proposal_formalization',
    'get_proposal_generic_video',
    'get_proposal_personalized_video',
    'get_proposal_template',
    'launch_proposal_to_platform',
    'list_clients',
    'list_diagnostics',
    'list_proposal_contract_snapshots',
    'list_proposal_contract_template_versions',
    'list_proposals',
    'log_proposal_activity',
    'prepare_proposal_formalization',
    'preview_proposal_contract_template_update',
    'preview_proposal_section_sync',
    'read_proposal_contract_snapshot',
    'reassign_proposal_project',
    'remove_partnership_program_video',
    'remove_proposal_generic_video',
    'remove_proposal_personalized_video',
    'render_proposal_email_markdown_pdf',
    'reorder_proposal_sections',
    'reset_proposal_defaults',
    'restore_default_partnership_program_video',
    'restore_default_proposal_generic_video',
    'restore_proposal_contract_snapshot',
    'restore_proposal_contract_template_version',
    'review_proposal_approval',
    'save_proposal_contract_negotiation',
    'send_branded_email',
    'send_custom_proposal_email',
    'send_multi_proposal',
    'send_proposal_documents',
    'send_proposal_formalization',
    'set_partnership_program_video',
    'set_partnership_program_video_visibility',
    'set_proposal_generic_video',
    'set_proposal_generic_video_visibility',
    'set_proposal_personalized_video',
    'update_client',
    'update_diagnostic',
    'update_diagnostic_section',
    'update_diagnostic_status',
    'update_email_template',
    'update_proposal',
    'update_proposal_contract',
    'update_proposal_contract_modality',
    'update_proposal_contract_template',
    'update_proposal_defaults',
    'update_proposal_from_json',
    'update_proposal_section',
    'update_proposal_service_settings',
    'update_proposal_settings',
    'update_proposal_stage',
    'update_proposal_status',
    'upload_proposal_document',
    # communications
    'create_folder',
    'create_platform_secure_link',
    'delete_folder',
    'get_secure_link_url',
    'list_folders',
    'list_secure_link_events',
    'list_secure_links',
    'update_folder',
    'update_secure_link',
    # content
    'create_blog_post',
    'delete_linktree_asset',
    'get_linktree_template_clicks',
    'list_blog_posts',
    'list_linktree_templates',
    'override_linktree_template_asset',
    'preview_linktree_template',
    'share_linktree_template',
    'update_blog_post',
    'upload_linktree_template',
    # tasks
    'archive_task',
    'create_task',
    'create_task_alert',
    'create_task_comment',
    'delete_task_alert',
    'delete_task_comment',
    'list_tasks',
    'reorder_task',
    'update_task',
})

DEFERRED_SCHEMA_BACKLOG = {
    # commercial
    'update_email_template': 'Esquema de proposal_operations/proposal_schemas: pertenece al otro agente de esta rama; pendiente de su barrido.',
    'update_proposal_defaults': 'Esquema de proposal_operations/proposal_schemas: pertenece al otro agente de esta rama; pendiente de su barrido.',
    'update_proposal_settings': 'Esquema de proposal_operations/proposal_schemas: pertenece al otro agente de esta rama; pendiente de su barrido.',
}
