# Generated by Django 6.1 on 2026-10-06 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_project_data_retention'),
        ('content', '0281_project_data_retention'),
        ('monitoring', '0002_case_monitoring__last_se_4418a8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='retention_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='content.projectretentioncontext'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.project'),
        ),
    ]
